"""Change for phone

Revision ID: fc649cbd7545
Revises: 07603424e0e4
Create Date: 2022-02-23 16:04:29.640873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc649cbd7545'
down_revision = '07603424e0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
